import {
    UsersIcon,
    BookOpenIcon,
    AcademicCapIcon,
    ChartBarIcon,
    ClipboardDocumentCheckIcon,
    Cog6ToothIcon,
    HomeIcon,
    UserGroupIcon,
    DocumentTextIcon,
    PlusIcon,
    ArrowTrendingUpIcon,
    CheckCircleIcon,
    ClockIcon,
    BuildingOfficeIcon,
    ShieldCheckIcon,
    PaintBrushIcon,
    DocumentCheckIcon,
    PlayCircleIcon,
    TrophyIcon,
    EyeIcon,
    PencilSquareIcon,
    TrashIcon,
    ArrowRightIcon,
    XMarkIcon,
    Bars3Icon,
    ChevronDownIcon,
    MagnifyingGlassIcon,
    BellIcon,
    ArrowPathIcon,
    ExclamationTriangleIcon,
    InformationCircleIcon,
    PhotoIcon,
    CloudArrowUpIcon,
    QuestionMarkCircleIcon,
    ListBulletIcon
} from '@heroicons/react/24/outline';

import {
    UsersIcon as UsersIconSolid,
    BookOpenIcon as BookOpenIconSolid,
    AcademicCapIcon as AcademicCapIconSolid,
    HomeIcon as HomeIconSolid,
    CheckCircleIcon as CheckCircleIconSolid
} from '@heroicons/react/24/solid';

export {
    UsersIcon,
    BookOpenIcon,
    AcademicCapIcon,
    ChartBarIcon,
    ClipboardDocumentCheckIcon,
    Cog6ToothIcon,
    HomeIcon,
    UserGroupIcon,
    DocumentTextIcon,
    PlusIcon,
    ArrowTrendingUpIcon,
    CheckCircleIcon,
    ClockIcon,
    BuildingOfficeIcon,
    ShieldCheckIcon,
    PaintBrushIcon,
    DocumentCheckIcon,
    PlayCircleIcon,
    TrophyIcon,
    EyeIcon,
    PencilSquareIcon,
    TrashIcon,
    ArrowRightIcon,
    XMarkIcon,
    Bars3Icon,
    ChevronDownIcon,
    MagnifyingGlassIcon,
    BellIcon,
    ArrowPathIcon,
    ExclamationTriangleIcon,
    InformationCircleIcon,
    PhotoIcon,
    CloudArrowUpIcon,
    QuestionMarkCircleIcon,
    ListBulletIcon,
    // Solid variants
    UsersIconSolid,
    BookOpenIconSolid,
    AcademicCapIconSolid,
    HomeIconSolid,
    CheckCircleIconSolid
};
